FROM soulter/astrbot@sha256:a28e76163b0c49e78b978a79d5b8b93f94ca955332b26dfa3a203a367d303e9c

RUN uv pip install --system "playwright==1.62.0" "funasr-onnx==0.4.2" "modelscope==1.39.1" \
    && python -m playwright install --with-deps chromium chromium-headless-shell
